### PR TITLE
Add option to pass user id_token to the overloaded userProfile in strategy

### PR DESCRIPTION
**Pull request by Nigh7Sh4de**
** READ THIS FIRST! **

#### Is this a security patch?

If you discover a security issue please create an issue stating you've discovered a security
issue but don't divulge the issue, one of the maintainers will respond with an email address
you can send the details to. Once the issue has been patched the details can be made public.

### Checklist

- [ X ] I have read the [CONTRIBUTING](https://github.com/passport-next/passport/blob/master/CONTRIBUTING.md) guidelines.
- [ X ] I have added test cases which verify the correct operation of this feature or patch.
- [  ] I have added documentation pertaining to this feature or patch.
- [ X ] The automated test suite (`$ make test`) executes successfully.
- [ X ] The automated code linting (`$ npm run-script lint`) executes successfully.

<hr />

I was implementing this to create a new strategy for Twitch authentication on the new API. The response on authentication includes an id_token param (which is a JWT) from which the user's profile may be parsed. So I added an option parseIdToken for Strategy which decides whether the overloadable userProfile receives an access token or an id token.

Not sure what documentation I should add for this. Please let me know if anything is missing.

### CODE REVIEW

**Comment by rwky** [comment]
Looks good :+1: just add docs to the readme here https://github.com/passport-next/passport-oauth2#strategy-options and it'll be good to merge.

**Comment by Nigh7Sh4de** [comment]
@rwky

**Comment by Nigh7Sh4de** [comment]
Oops misclick, but I've updated the docs

**Comment by rwky** [comment]
Excellent, I'll check this out asap.

**Review by rwky — APPROVED** [review]

**Comment by rwky** [comment]
Published in v2.1.0

**Pull request merged**
